### ISSUE TITLE
expecting closing tag for the "block"

### ISSUE THREAD

**Issue by SBordier44** [Discutea/DForumBundle#12]
Unexpected "stylesheets" tag (expecting closing tag for the "block" tag defined near line 6) in DForumBundle::Post\edit_post.html.twig at line 6.

Sur Symfony  3.1

Bonne continuation :)

**Comment by Strategy47** [comment]
Bonjour, 

Ce problème vient de votre override je pense car la balise est bien fermée ligne 9 et 10

https://github.com/Discutea/DForumBundle/blob/1.0/Resources/views/Post/edit_post.html.twig#L10

Symfony 3.1.5 cela fonctionne bien chez moi 
Pouvez vous me confirmer cette hypothèse SVP ?

**Comment by SBordier44** [comment]
Mon override, que voulez-vous dire ?
J'ai ceci d'affiché sous l'erreur "500 Internal Server Error - Twig_Error_Syntax"
Mes packages (symfony, twig, etc..) sont tous à la dernière version stable.

**Comment by Strategy47** [comment]
Vous devez créer les vues par [override](http://symfony.com/doc/current/bundles/override.html) je pense que la balise est mal fermée dans votre forum bundle.

Voici un exemple d'utilisation https://github.com/IRCz/IRCz/tree/master/src/IRCz/ForumBundle

**Comment by SBordier44** [comment]
J'ai installé votre bundle depuis Composer sur mon project Symfony en suivant les instructions que vous donnez sur votre page gitHub.
Donc si je comprend bien, il faut que je fasse quelque chose de plus ? Sachant que le reste fonctionne très bien :)
Ça ne fait pas très longtemps que je suis sur Symfony, peut-être ais-je oublié quelque chose :)

**Comment by Strategy47** [comment]
Oops désolé je viens de comprendre en regardant mieux le code. Le bundle est en fait dépendant du bundle [assetic](https://symfony.com/doc/current/assetic.html)  j'ai tellement l'habitude d'utiliser ce bundle que je m'en suis machinalement servi en codant le forum. Je vais retirer cette dépendance le plus rapidement possible. 

Désolé

**Comment by SBordier44** [comment]
Ce n'est pas grave, après je pouvez garder assetic, ce n'est pas une mauvaise chose :)
Pensez juste à l'ajouter dans vos require Composer :)
Je vais l'installer de mon coté ;)

**Comment by Strategy47** [comment]
Je retirerai plutôt cette dépendance car tout le monde ne s'en sert pas :) 

Merci de votre contribution

**Comment by SBordier44** [comment]
Parfait ! Ça fonctionne nickel avec assetic :)
C'était tout bête et j'aurais du y penser :)

Pas de quoi ;)

**Comment by mariamcheikh** [comment]
Bonjour .
 il m'affiche la même erreur que NUBoxDevCom mais en fait je ne sais pas quoi faire exactement pour qu'il fonctionne ( je suis encore débutante )

**Comment by Strategy47** [comment]
Il suffit d'installer assetic :) Je vais retirer cette dépendance dès que possible mais j'ai beaucoup de travail en ce moment.
