### ISSUE TITLE
Search forum topics

### ISSUE THREAD

**Issue by mistris** [Discutea/DForumBundle#17]
Hi!
Will you implement functionality to search forum topics by topic.title and forum topics by posts.content?

**Comment by Strategy47** [comment]
Hi,
Improvements are planned on a new branch but a search system is not included.

I reckon that such a system should not necessarily be a part of the forum features but rather an independant application based on the Forum bundle entities

Https://github.com/search?utf8=%E2%9C%93&q=searchbundle

Regards
