### ISSUE TITLE
Bbcode use (with FMBbcodeBundle)

### ISSUE THREAD

**Issue by nils-van-zuijlen** [Discutea/DForumBundle#18]
Hello,
How can I use [FMBbcodeBundle](https://github.com/helios-ag/FMBbCodeBundle) in order to parse posts content?
Must I override some view? If yes, which?

**Comment by Strategy47** [comment]
Hi,
Yes it is possible to use it.
Look at the example on this [repository](https://github.com/IRCz/IRCz/tree/master/src/IRCz/ForumBundle)
It is necessary to parse the content of posts.
