### ISSUE TITLE
Bundle non créé à l'installation

### ISSUE THREAD

**Issue by Mikaelthomas** [Discutea/DForumBundle#28]
Après l'installation du Bundle, aucune création du bundle n'est effectué dans le Symfony...

**Comment by Strategy47** [comment]
Je suppose que c'est résolu ? 
Le bundle est créé dans le dossier vendor/discutea/ pour faire un héritage vous devez créer votre propre bundle.

http://symfony.com/doc/current/bundles/inheritance.html
