### ISSUE TITLE
block stylesheets erased

### ISSUE THREAD

**Issue by mysterty** [Discutea/DForumBundle#3]
Block stylesheets is erased in index.html.twig file.

parent() should be used plus it'd be better to set style in separate css file

**Comment by Strategy47** [comment]
You should not use the views of the bundle. This is used to make a more attractive presentation. Create an override http://symfony.com/doc/current/cookbook/bundles/inheritance.html
For more help on override please join support http://kiwi.ircz.fr/

**Comment by mysterty** [comment]
In fact it is what i do, but you could provide a minimal and more modularise integration like page/page_content, so users don't have to override 100% of the view. ;)
