### ISSUE TITLE
there is no bin how u php bin/console doctrine:schema:update --force !!!!

### ISSUE THREAD

**Issue by jomjom841** [Discutea/DForumBundle#39]

**Comment by Strategy47** [comment]
what is the version of symfony do you use?

**Comment by jomjom841** [comment]
symfony 3.3

**Comment by jomjom841** [comment]
do u have a link for a working forum  symfony 3 without configuration and thanks I really need it

**Comment by Strategy47** [comment]
Please, read symfony's documentation and close this. 
https://symfony.com/doc/3.3/doctrine.html

Symfony is a framework for developers you must learn how to use it!

If this is too difficult for you, redirect to CMS ex: https://www.phpbb.com/

**Comment by jomjom841** [comment]
I did all steps just I can't  use  php bin/console doctrine:schema:update --force

**Comment by jomjom841** [comment]
Could not open input file: bin/console

**Comment by jomjom841** [comment]
could u configure it for me with team viewer ?
