### ISSUE TITLE
Problème de traduction

### ISSUE THREAD

**Issue by Sdtcn67** [Discutea/DForumBundle#40]
bonjour,

j'ai pu installer le bundle sans difficultés mais lors de son utilisation je n'avais pas les bonnes traductions sur ma page.
je m'explique : 
au lieu de : "Administrer les catégories et les forums."
j'avais : "discutea.forum.category.manage"

J'ai eu beau chercher pendant plusieurs jours, pas moyen de trouver la raison du problème, sauf aujourd'hui.
Dans tous les fichiers messages.XX.xlf, source-language est égal à "en" .
Il m'a donc suffit de modifier le fichier qui m’intéressait en l’occurrence messages.fr.xlf et de modifier le sosurce-language="en" en ="fr".
Bref, vous aurez bien compris, je pense, le problème qui n'est qu'un tout petit bug face à l'ampleur du travail effectué mais qui mérite peut-être une petite correction car il "pourrit" la vie de débutant comme moi.
Un grand merci

**Comment by CyrilCharlier** [comment]
Hello Sdtcn67,

Ce n'est pas un bug je pense, tu n'avais sûrement pas activé la traduction dans la config : 

```yaml
framework:
    translator: ~
```
et tu n'auras pas besoin de modifier le fichier "source-language".

cdt,
